# Spec file auto-generated from harbour-slackship.yaml
# Do not edit this file manually

Name:       harbour-slackship
Summary:    Native Slack client for Sailfish OS
Version:    0.1.0
Release:    1
Group:      Applications/Internet
License:    GPLv3
URL:        https://github.com/yourusername/harbour-slackship
Source0:    %{name}-%{version}.tar.bz2

Requires:   sailfishsilica-qt5 >= 1.0.0
Requires:   qt5-qtnetwork
Requires:   qt5-qtwebsockets
Requires:   qt5-qtsql
Requires:   nemonotifications-qt5

BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5WebSockets)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  desktop-file-utils

%description
SlackShip is a native Slack client for Sailfish OS that provides
full access to your Slack workspaces with a native UI experience.

Features:
- Real-time messaging via WebSocket
- Multiple workspace support
- Channels, DMs, and groups
- Message threads and reactions
- File sharing
- Push notifications


%prep
%setup -q -n %{name}-%{version}

%build
%qmake5 harbour-slackship.pro

make %{?_smp_mflags}

%install
rm -rf %{buildroot}
%qmake5_install

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
